apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
]

apps/departamentos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'departamentos'


urlpatterns = [
    path('novo-departamento/', login_required(NovoDepartamento.as_view()), name='novo_departamento'),
    path('lista-departamentos/', login_required(ListaDepartamentos.as_view()), name='lista_departamentos'),
    path('detalhe-departamento/<int:pk>/', login_required(DetalheDepartamento.as_view()), name='detalhe_departamento'),
    path('editar-departamento/<int:pk>/', login_required(EditarDepartamento.as_view()), name='editar_departamento'),
    path('deletar-departamento/<int:pk>/', login_required(DeletarDepartamento.as_view()), name='deletar_departamento'),
]

gerdoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('admin/', admin.site.urls),
]

apps/departamentos/models.py
from django.db import models
from apps.empresas.models import Empresas


class Departamentos(models.Model):
    nome = models.CharField('Nome', max_length=100)
    empresa = models.ForeignKey(Empresas, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nome

apps/departamentos/forms.py
from django import forms
from apps.departamentos.models import Departamentos


class DepartamentosForm(forms.ModelForm):
    nome = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    widget = {
        'empresa': forms.Select(
            attrs={
                'class': 'form-control',
            }
        ),
    }

    class Meta:
        model = Departamentos
        fields = (
            'nome',
            'empresa',
        )

apps/departamentos/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)


class NovoDepartamento(CreateView):
    form_class = DepartamentosForm
    template_name = 'departamentos/novo_departamento.html'

    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.empresa
        departamento.save()
        return super(NovoDepartamento, self).form_valid(form)

    def get_success_url(self):
        return reverse('departamentos:lista_departamentos')


class ListaDepartamentos(ListView):
    model = Departamentos
    template_name = 'departamentos/lista_departamentos.html'


class DetalheDepartamento(DetailView):
    model = Departamentos
    template_name = 'departamentos/detalhe_departamento.html'


class EditarDepartamento(UpdateView):
    model = Departamentos
    template_name = 'departamentos/editar_departamento.html'
    fields = (
        'nome',
        'empresa',
    )


class DeletarDepartamento(DeleteView):
    model = Departamentos
    template_name = 'departamentos/confirme_delete_departamento.html'
    success_url = reverse_lazy('departamentos:lista_departamentos')

apps/departamentos/templates/departamentos/confirme_delete_departamento.html
{% extends 'base.html' %}

{% block title %}Deletar Departamento{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Departamentos</h3>
			<h6>Deletar Departamento</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'departamentos:lista_departamentos' %}">Lista de Departamentos</a> /
					<a href="{% url 'departamentos:detalhe_departamento' object.pk %}">Detalhe do Departamentos</a> /
					Deletar Departamento
				</p>
			</div>
			<div class='card-body'>
				<form action="" method="POST" class="form-delete">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div>
                            <h2>Tem certeza que deseja excluir "<strong>{{ object.nome }}</strong>"?</h2>
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="far fa-check-circle"></i>
                                Sim
                            </button>
                            <a href="{% url 'departamentos:detalhe_departamento' object.pk %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Não
                            </a>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/departamentos/templates/departamentos/detalhe_departamento.html
{% extends 'base.html' %}

{% block title %}Informações do Departamento{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Departamentos</h3>
			<h6>Informações do Departamento</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'departamentos:lista_departamentos' %}">Lista de Departamentos</a> /
					Informações do Departamento
				</p>
			</div>
			<div class='card-body'>
				<div>
					<h4>{{ object.nome }}</h4>
				</div>
				<ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <strong>Nome:</strong>
                        {{ object.nome }}
                    </li>
                    <li class="list-group-item">
                        <strong>Empresa:</strong>
                        {{ object.empresa }}
                    </li>
                </ul>
                <div class="button-detail col-md-12">
                    <a href="{% url 'departamentos:deletar_departamento' object.pk %}" type="button" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        Excluir
                    </a>
                    <a href="{% url 'departamentos:editar_departamento' object.pk %}" type="button" class="btn btn-warning">
                        <i class="fas fa-edit"></i>
                        Editar
                    </a>
                </div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/departamentos/templates/departamentos/editar_departamento.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Departamentos</h3>
			<h6>Editar Departamento</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'departamentos:lista_departamentos' %}">Lista de Departamentos</a> /
					<a href="{% url 'departamentos:detalhe_departamento' object.pk %}">Detalhe do Departamento</a> /
					Editar Departamento
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            {% bootstrap_label 'Nome<span>*</span>' label_for='id_nome' %}
                            {% bootstrap_field form.nome size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Selecionar Empresa<span>*</span>' label_for='id_empresa' %}
                            {% bootstrap_field form.empresa size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'departamentos:lista_departamentos' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/departamentos/templates/departamentos/lista_departamentos.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Departamentos</h3>
			<h6>Lista de Departamentos</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header'>
				<form action="." method="GET" class="d-flex navbar-form">
					<div class="form-group">
						<input class="form-control me-2" type="search" name="busca" value="" placeholder="Pesquisar" aria-label="Search">
					</div>
					<button class="btn btn-light" type="submit">
						<span class="fa fa-search"></span>
					</button>
				</form>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					Lista de Departamentos
				</p>
			</div>
			<div class='card-body'>
				{% if object_list %}
					<div class="table-responsive">
						<table class="table custom-table">
							<thead class="table-dark">
								<tr>
									<th scope="col">Nome</th>
									<th scope="col">Empresa</th>
								</tr>
							</thead>
							<tbody>
							{% for departamento in object_list %}
								<tr scope="row">
									<td>
										<a href="{% url 'departamentos:detalhe_departamento' departamento.pk %}">{{ departamento.nome }}</a>
									</td>
									<td>{{ departamento.empresa }}</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<div class="alert alert-danger alert-list" role="alert">
						<div class="alert-title">
							<i class="fas fa-exclamation-circle alert-icon"></i>
						</div>
						<div class="alert-content">
							Departamento não Cadastrado!
						</div>
					</div>
				{% endif %}
				<div class="table-button">
					<a href="{% url 'departamentos:novo_departamento' %}" class="btn btn-success" title="Adicionar departamento">
						<i class="fas fa-plus"></i>
						Departamento
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/departamentos/templates/departamentos/novo_departamento.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Departamentos</h3>
			<h6>Cadastro de Departamento</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'departamentos:lista_departamentos' %}">Lista de Departamentos</a> /
					Cadastro de Departamento
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            {% bootstrap_label 'Nome<span>*</span>' label_for='id_nome' %}
                            {% bootstrap_field form.nome size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Selecionar Empresa<span>*</span>' label_for='id_empresa' %}
                            {% bootstrap_field form.empresa size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'departamentos:lista_departamentos' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}