apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
]

apps/departamentos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'departamentos'


urlpatterns = [
    path('novo-departamento/', login_required(NovoDepartamento.as_view()), name='novo_departamento'),
    path('lista-departamentos/', login_required(ListaDepartamentos.as_view()), name='lista_departamentos'),
    path('detalhe-departamento/<int:pk>/', login_required(DetalheDepartamento.as_view()), name='detalhe_departamento'),
    path('editar-departamento/<int:pk>/', login_required(EditarDepartamento.as_view()), name='editar_departamento'),
    path('deletar-departamento/<int:pk>/', login_required(DeletarDepartamento.as_view()), name='deletar_departamento'),
]

apps/funcionarios/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'funcionarios'


urlpatterns = [
    path('novo-funcionario/', NovoFuncionario.as_view(), name='novo_funcionario'),
    path('lista-funcionarios/', ListaFuncionarios.as_view(), name='lista_funcionarios'),
    path('detalhe-funcionario/<int:pk>/', DetalheFuncionario.as_view(), name='detalhe_funcionario'),
    path('editar-funcionario/', EditarFuncionario.as_view(), name='editar_funcionario'),
]

gerdoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('admin/', admin.site.urls),
]

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from apps.departamentos.models import Departamentos
from apps.empresas.models import Empresas


class Funcionarios(AbstractUser):
    empresa = models.ForeignKey(Empresas, on_delete=models.PROTECT, null=True, blank=True)
    cpf = models.CharField('CPF', max_length=14, blank=True, null=True)
    departamento = models.ForeignKey(Departamentos, on_delete=models.PROTECT, blank=True, null=True)
    logradouro = models.CharField('endereco', max_length=200, blank=True, null=True)
    numero = models.CharField('Numero', max_length=10, blank=True, null=True)
    bairro = models.CharField('Bairro', max_length=100, blank=True, null=True)
    cep = models.CharField('CEP', max_length=9, blank=True, null=True)
    uf = models.CharField('UF', max_length=2)
    cidade = models.CharField('Cidade', max_length=100, blank=True, null=True)
    telefone = models.CharField('telefone', max_length=15, blank=True, null=True)

    def __str__(self):
        return self.username

apps/empresas/forms.py
from django import forms
from apps.empresas.models import Empresas


class EmpresasForm(forms.ModelForm):
    razao_social = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    nome_fantasia = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    cnpj = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    endereco = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    telefone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    class Meta:
        model = Empresas
        fields = (
            'razao_social',
            'nome_fantasia',
            'cnpj',
            'endereco',
            'email',
            'telefone',
        )

apps/funcionarios/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from apps.funcionarios.models import Funcionarios


class FuncionarioCreateForm(UserCreationForm):
    class Meta:
        model = Funcionarios
        fields = (
            'first_name',
            'last_name',
            'cpf',
            'departamento',
            'logradouro',
            'numero',
            'bairro',
            'cep',
            'uf',
            'cidade',
            'email',
            'telefone',
            'username',
            'empresa',
        )


class FuncionarioChangeForm(UserChangeForm):
    class Meta:
        model = Funcionarios
        fields = (
            'first_name',
            'last_name',
            'cpf',
            'departamento',
            'logradouro',
            'numero',
            'bairro',
            'cep',
            'uf',
            'cidade',
            'email',
            'telefone',
        )

apps/funcionarios/views.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.shortcuts import reverse
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)


class NovoFuncionario(CreateView):
    form_class = FuncionarioCreateForm
    template_name = 'funcionarios/novo_funcionario.html'

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.empresa
        funcionario.save()
        return super(NovoFuncionario, self).form_valid(form)

    def get_success_url(self):
        return reverse('core:home')


class ListaFuncionarios(ListView):
    model = Funcionarios
    template_name = 'funcionarios/lista_funcionarios.html'


class DetalheFuncionario(DetailView):
    model = Funcionarios
    template_name = 'funcionarios/detalhe_funcionario.html'


class EditarFuncionario(UpdateView):
    form_class = FuncionarioChangeForm
    template_name = 'funcionarios/editar_funcionario.html'
    success_url = reverse_lazy('funcionarios:detalhe_funcionario')

    def get_object(self):
        return self.request.user

apps/funcionarios/templates/funcionarios/detalhe_funcionario.html
{% extends 'base.html' %}

{% block title %}Informações do Funcionário{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Funcionários</h3>
			<h6>Informações do Funcionário</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'funcionarios:lista_funcionarios' %}">Lista de Funcionários</a> /
					Informações do Funcionário
				</p>
			</div>
			<div class='card-body'>
				<div>
					<h4>{{ object.first_name }} {{ object.last_name }}</h4>
				</div>
				<ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <strong>Nome:</strong>
                        {{ object.first_name }} {{ object.last_name }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cpf:</strong>
                        {{ object.cpf }}
                    </li>
                    <li class="list-group-item">
                        <strong>Departamento:</strong>
                        {{ object.departamento }}
                    </li>
                    <li class="list-group-item">
                        <strong>Logradouro:</strong>
                        {{ object.logradouro }}
                    </li>
                    <li class="list-group-item">
                        <strong>Número:</strong>
                        {{ object.numero }}
                    </li>
                    <li class="list-group-item">
                        <strong>Bairro:</strong>
                        {{ object.bairro }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cep:</strong>
                        {{ object.cep }}
                    </li>
                    <li class="list-group-item">
                        <strong>UF:</strong>
                        {{ object.uf }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cidade:</strong>
                        {{ object.cidade }}
                    </li>
                    <li class="list-group-item">
                        <strong>E-mail:</strong>
                        {{ object.email }}
                    </li>
                    <li class="list-group-item">
                        <strong>Telefone:</strong>
                        {{ object.telefone }}
                    </li>
                </ul>
                <div class="button-detail col-md-12">
                    <a href="{% url 'departamentos:deletar_departamento' object.pk %}" type="button" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        Excluir
                    </a>
                    <a href="{% url 'funcionarios:editar_funcionario' %}" type="button" class="btn btn-warning">
                        <i class="fas fa-edit"></i>
                        Editar
                    </a>
                </div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/funcionarios/templates/funcionarios/editar_funcionario.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Funcionários</h3>
			<h6>Editar Funcionário</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'funcionarios:lista_funcionarios' %}">Lista de Funcionários</a> /
					<a href="{% url 'funcionarios:detalhe_funcionario' object.pk %}">Detalhe do Funcionário</a> /
					Editar Funcionário
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            {% bootstrap_label 'Primeiro Nome<span>*</span>' label_for='id_first_name' %}
                            {% bootstrap_field form.first_name size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Último Nome<span>*</span>' label_for='id_last_name' %}
                            {% bootstrap_field form.last_name size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Cpf<span>*</span>' label_for='id_cpf' %}
                            {% bootstrap_field form.cpf size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Selecionar Departamento<span>*</span>' label_for='id_departamento' %}
                            {% bootstrap_field form.departamento size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Logradouro<span>*</span>' label_for='id_logradouro' %}
                            {% bootstrap_field form.logradouro size='sm' show_label=false %}
                        </div>
                        <div class="col-md-2">
                            {% bootstrap_label 'Número<span>*</span>' label_for='id_numero' %}
                            {% bootstrap_field form.numero size='sm' show_label=false %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_label 'Bairro<span>*</span>' label_for='id_bairro' %}
                            {% bootstrap_field form.bairro size='sm' show_label=false %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_label 'Cep<span>*</span>' label_for='id_cep' %}
                            {% bootstrap_field form.cep size='sm' show_label=false %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_label 'Uf<span>*</span>' label_for='id_uf' %}
                            {% bootstrap_field form.uf size='sm' show_label=false %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_label 'Cidade<span>*</span>' label_for='id_cidade' %}
                            {% bootstrap_field form.cidade size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'E-mail<span>*</span>' label_for='id_email' %}
                            {% bootstrap_field form.email size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Telefone<span>*</span>' label_for='id_telefone' %}
                            {% bootstrap_field form.telefone size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'funcionarios:lista_funcionarios' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/funcionarios/templates/funcionarios/lista_funcionarios.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Funcionários</h3>
			<h6>Lista de Funcionários</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header'>
				<form action="." method="GET" class="d-flex navbar-form">
					<div class="form-group">
						<input class="form-control me-2" type="search" name="busca" value="" placeholder="Pesquisar" aria-label="Search">
					</div>
					<button class="btn btn-light" type="submit">
						<span class="fa fa-search"></span>
					</button>
				</form>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					Lista de Funcionários
				</p>
			</div>
			<div class='card-body'>
				{% if object_list %}
						<div class="table-responsive">
							<table class="table custom-table">
								<thead class="table-dark">
									<tr>
										<th scope="col">Nome</th>
										<th scope="col">Cpf</th>
										<th scope="col">Departamento</th>
										<th scope="col">E-mail</th>
										<th scope="col">Telefone</th>
									</tr>
								</thead>
								<tbody>
								{% for funcionario in object_list %}
									<tr scope="row">
										<td>
											<a href="{% url 'funcionarios:detalhe_funcionario' funcionario.pk %}">
												{{ funcionario.first_name }} {{ funcionario.last_name }}
											</a>
										</td>
										<td>{{ funcionario.cpf }}</td>
										<td>{{ funcionario.departamento }}</td>
										<td>{{ empresa.email }}</td>
										<td>{{ empresa.telefone }}</td>
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
				{% else %}
					<div class="alert alert-danger alert-list" role="alert">
						<div class="alert-title">
							<i class="fas fa-exclamation-circle alert-icon"></i>
						</div>
						<div class="alert-content">
							Funcionário não Cadastrado!
						</div>
					</div>
				{% endif %}
				<div class="table-button">
					<a href="{% url 'funcionarios:novo_funcionario' %}" class="btn btn-success" title="Adicionar funcionário">
						<i class="fas fa-plus"></i>
						Funcionário
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/funcionarios/templates/funcionarios/novo_funcionario.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Funcionários</h3>
			<h6>Cadastro de Funcionário</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'funcionarios:lista_funcionarios' %}">Lista de Funcionários</a> /
					Cadastro de Funcionário
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-12">
                            {% bootstrap_label 'Primeiro Nome<span>*</span>' label_for='id_first_name' %}
                            {% bootstrap_field form.first_name size='sm' show_label=false %}
                        </div>
                        <div class="col-md-12">
                            {% bootstrap_label 'Último Nome<span>*</span>' label_for='id_last_name' %}
                            {% bootstrap_field form.last_name size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Usuário<span>*</span>' label_for='id_username' %}
                            {% bootstrap_field form.username size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Endereço<span>*</span>' label_for='id_endereco' %}
                            {% bootstrap_field form.endereco size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'E-mail<span>*</span>' label_for='id_email' %}
                            {% bootstrap_field form.email size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Cpf<span>*</span>' label_for='id_cpf' %}
                            {% bootstrap_field form.cpf size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Telefone<span>*</span>' label_for='id_telefone' %}
                            {% bootstrap_field form.telefone size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Selecionar Departamento<span>*</span>' label_for='id_departamento' %}
                            {% bootstrap_field form.departamento size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Senha<span>*</span>' label_for='id_password1' %}
                            {% bootstrap_field form.password1 size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Confirmar Senha<span>*</span>' label_for='id_password2' %}
                            {% bootstrap_field form.password2 size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'funcionarios:lista_funcionarios' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}