apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
]

apps/departamentos/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'departamentos'


urlpatterns = [
    path('novo-departamento/', login_required(NovoDepartamento.as_view()), name='novo_departamento'),
    path('lista-departamentos/', login_required(ListaDepartamentos.as_view()), name='lista_departamentos'),
    path('detalhe-departamento/<int:pk>/', login_required(DetalheDepartamento.as_view()), name='detalhe_departamento'),
    path('editar-departamento/<int:pk>/', login_required(EditarDepartamento.as_view()), name='editar_departamento'),
    path('deletar-departamento/<int:pk>/', login_required(DeletarDepartamento.as_view()), name='deletar_departamento'),
]

apps/empresas/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'empresas'


urlpatterns = [
    path('nova-empresa/', login_required(NovaEmpresa.as_view()), name='nova_empresa'),
    path('lista-empresas/', login_required(ListaEmpresas.as_view()), name='lista_empresas'),
    path('detalhe-empresa/<int:pk>/', login_required(DetalheEmpresa.as_view()), name='detalhe_empresa'),
    path('editar-empresa/<int:pk>/', login_required(EditarEmpresa.as_view()), name='editar_empresa'),
    path('deletar-empresa/<int:pk>/', login_required(DeletarEmpresa.as_view()), name='deletar_empresa'),
]

apps/funcionarios/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *


app_name = 'funcionarios'


urlpatterns = [
    path('novo-funcionario/', NovoFuncionario.as_view(), name='novo_funcionario'),
    path('lista-funcionarios/', ListaFuncionarios.as_view(), name='lista_funcionarios'),
    path('detalhe-funcionario/<int:pk>/', DetalheFuncionario.as_view(), name='detalhe_funcionario'),
    path('editar-funcionario/', EditarFuncionario.as_view(), name='editar_funcionario'),
]

gerdoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block title %}{% endblock %}

    <link rel="shortcut icon" type="image/x-icon" href="">
    <!-- Local CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/scss/apps.css' %}">
</head>
<body>
    <div class='dashboard'>
        <div class="dashboard-nav bg-dark">
            <header>
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="{% url 'core:home' %}" class="brand-logo">
                    <img src="{% static 'assets/media/img/logo/marka-logo-80.png' %}" alt="">
                </a>
            </header>
            <div class="nav-item-divider"></div>
            {% with url_name=request.resolver_match.url_name %}
            <nav class="dashboard-nav-list">
                <a href="{% url 'core:home' %}" class="dashboard-nav-item {% if url_name == 'home' %}active{% endif %}">
                    <i class="fas fa-home"></i>
                    Home
                </a>
                <a href="{% url 'empresas:lista_empresas' %}" class="dashboard-nav-item {% if url_name == 'lista_empresas' or url_name == 'nova_empresa' or url_name == 'detalhe_empresa' or url_name == 'editar_empresa' or url_name == 'deletar_empresa' %}active{% endif %}">
                    <i class="fas fa-building"></i>
                    Empresas
                </a>
                <a href="{% url 'departamentos:lista_departamentos' %}" class="dashboard-nav-item {% if url_name == 'lista_departamentos' or url_name == 'novo_departamento' or url_name == 'detalhe_departamento' or url_name == 'editar_departamento' or url_name == 'deletar_departamento' %}active{% endif %}">
                    <i class="fas fa-boxes"></i>
                    Departamentos 
                </a>
                <a href="{% url 'funcionarios:lista_funcionarios' %}" class="dashboard-nav-item">
                    <i class="fas fa-id-badge"></i> 
                    Funcionários 
                </a>
                <a href="" class="dashboard-nav-item">
                    <i class="fas fa-file-word"></i> 
                    Documentos 
                </a>
                <!--
                <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                        <i class="fas fa-photo-video"></i> 
                        Media 
                    </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a href="#" class="dashboard-nav-dropdown-item">All</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Recent</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Images</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Video</a>
                    </div>
                </div>
                <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                        <i class="fas fa-users"></i> 
                        Users 
                    </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a href="#" class="dashboard-nav-dropdown-item">All</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Subscribed</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Non-subscribed</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Banned</a>
                        <a href="#" class="dashboard-nav-dropdown-item">New</a>
                    </div>
                </div>
                <div class='dashboard-nav-dropdown'>
                    <a href="#!" class="dashboard-nav-item dashboard-nav-dropdown-toggle">
                        <i class="fas fa-money-check-alt"></i> 
                        Payments 
                    </a>
                    <div class='dashboard-nav-dropdown-menu'>
                        <a href="#" class="dashboard-nav-dropdown-item">All</a>
                        <a href="#" class="dashboard-nav-dropdown-item">Recent</a>
                        <a href="#" class="dashboard-nav-dropdown-item"> Projections</a>
                    </div>
                </div>
                <a href="#" class="dashboard-nav-item">
                    <i class="fas fa-cogs"></i> 
                    Settings 
                </a>
                <a href="#" class="dashboard-nav-item">
                    <i class="fas fa-user"></i> 
                    Profile 
                </a>
                -->
              <div class="nav-item-divider"></div>
              <a href="#" class="dashboard-nav-item">
                <i class="fas fa-user-circle"></i> 
                  Perfil
              </a>
              <a href="#" class="dashboard-nav-item">
                <i class="fas fa-key"></i>
                Redefinir Senha
              </a>
              <a href="#" class="dashboard-nav-item">
                  <i class="fas fa-sign-out-alt"></i> 
                  Sair
                </a>
            </nav>
            {% endwith %}
        </div>
        <div class='dashboard-app'>
            <header class='dashboard-toolbar'>
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <div class="user">
                    <img src="{% static 'assets/media/img/icon/user-64.png' %}" alt="">
                    <span>{{ user }}</span>
                </div>
            </header>
            <div class='dashboard-content'>
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <!-- CDN JS -->
    <!-- Jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Mask JS -->
    <Script type="text/javascript" src="{% static '/assets/js/jquery/jquery.mask.min.js' %}"></Script>

    <!-- Local JS -->
    <Script type="text/javascript" src="{% static '/assets/js/custom-fields.js' %}"></Script>
    <Script type="text/javascript" src="{% static '/assets/js/apps.js' %}"></Script>
    {% block scripts %}{% endblock %}
</body>
</html>