apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
]

apps/empresas/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *

app_name = 'empresas'


urlpatterns = [
    path('nova-empresa/', login_required(NovaEmpresa.as_view()), name='nova_empresa'),
    path('lista-empresas/', login_required(ListaEmpresas.as_view()), name='lista_empresas'),
    path('detalhe-empresa/<int:pk>/', login_required(DetalheEmpresa.as_view()), name='detalhe_empresa'),
    path('editar-empresa/<int:pk>/', login_required(EditarEmpresa.as_view()), name='editar_empresa'),
    path('deletar-empresa/<int:pk>/', login_required(DeletarEmpresa.as_view()), name='deletar_empresa'),
]

gerdoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('admin/', admin.site.urls),
]

apps/empresas/models.py
from django.db import models


class Empresas(models.Model):
    razao_social = models.CharField('Razao Social', max_length=100, unique=True)
    nome_fantasia = models.CharField('Nome Fantasia', max_length=100)
    cnpj = models.CharField('CNPJ', max_length=18, unique=True)
    logradouro = models.CharField('Endereco', max_length=200)
    numero = models.CharField('Numero', max_length=10, blank=True, null=True)
    bairro = models.CharField('Bairro', max_length=100, blank=True, null=True)
    cep = models.CharField('CEP', max_length=9, blank=True, null=True)
    cidade = models.CharField('Cidade', max_length=100, blank=True, null=True)
    uf = models.CharField('UF', max_length=2)
    email = models.EmailField('Email')
    telefone = models.CharField('Telefone', max_length=15)

    def __str__(self):
        return self.razao_social

apps/empresas/forms.py
from django import forms
from apps.empresas.models import Empresas


class EmpresasForm(forms.ModelForm):
    razao_social = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    nome_fantasia = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    cnpj = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    endereco = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    telefone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '',
            }
        )
    )

    class Meta:
        model = Empresas
        fields = (
            'razao_social',
            'nome_fantasia',
            'cnpj',
            'endereco',
            'email',
            'telefone',
        )

apps/empresas/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)


class NovaEmpresa(CreateView):
    form_class = EmpresasForm
    template_name = 'empresas/nova_empresa.html'

    def get_success_url(self):
        return reverse('empresas:lista_empresas')


class ListaEmpresas(ListView):
    model = Empresas
    template_name = 'empresas/lista_empresas.html'


class DetalheEmpresa(DetailView):
    model = Empresas
    template_name = 'empresas/detalhe_empresa.html'


class EditarEmpresa(UpdateView):
    model = Empresas
    template_name = 'empresas/editar_empresa.html'
    fields = (
        'razao_social',
        'nome_fantasia',
        'cnpj',
        'endereco',
        'email',
        'telefone',
    )


class DeletarEmpresa(DeleteView):
    model = Empresas
    template_name = 'empresas/confirme_delete_empresa.html'
    success_url = reverse_lazy('empresas:lista_empresas')

apps/empresas/templates/empresas/confirme_delete_empresa.html
{% extends 'base.html' %}

{% block title %}Deletar Empresa{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Empresas</h3>
			<h6>Deletar Empresa</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'empresas:lista_empresas' %}">Lista de Empresas</a> /
					<a href="{% url 'empresas:detalhe_empresa' object.pk %}">Detalhe da Empresa</a> /
					Deletar Empresa
				</p>
			</div>
			<div class='card-body'>
				<form action="" method="POST" class="form-delete">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div>
                            <h2>Tem certeza que deseja excluir "<strong>{{ object.nome_fantasia }}</strong>"?</h2>
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="far fa-check-circle"></i>
                                Sim
                            </button>
                            <a href="{% url 'empresas:detalhe_empresa' object.pk %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Não
                            </a>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/empresas/templates/empresas/detalhe_empresa.html
{% extends 'base.html' %}

{% block title %}Informações da Empresa{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Empresas</h3>
			<h6>Informações da Empresa</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'empresas:lista_empresas' %}">Lista de Empresas</a> /
					Informações da Empresa
				</p>
			</div>
			<div class='card-body'>
				<div>
					<h4>{{ object.nome_fantasia }}</h4>
				</div>
				<ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <strong>Razão Social:</strong>
                        {{ object.razao_social }}
                    </li>
                    <li class="list-group-item">
                        <strong>Nome Fantasia:</strong>
                        {{ object.nome_fantasia }}
                    </li>
                    <li class="list-group-item">
                        <strong>Cnpj:</strong>
                        {{ object.cnpj }}
                    </li>
                    <li class="list-group-item">
                        <strong>Endereço:</strong>
                        {{ object.endereco }}
                    </li>
                    <li class="list-group-item">
                        <strong>E-mail:</strong>
                        {{ object.email }}
                    </li>
                    <li class="list-group-item">
                        <strong>Telefone:</strong>
                        {{ object.telefone }}
                    </li>
                </ul>
                <div class="button-detail col-md-12">
                    <a href="{% url 'empresas:deletar_empresa' object.pk %}" type="button" class="btn btn-danger">
                        <i class="fas fa-trash"></i>
                        Excluir
                    </a>
                    <a href="{% url 'empresas:editar_empresa' object.pk %}" type="button" class="btn btn-warning">
                        <i class="fas fa-edit"></i>
                        Editar
                    </a>
                </div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/empresas/templates/empresas/editar_empresa.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Empresas</h3>
			<h6>Editar Empresa</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'empresas:lista_empresas' %}">Lista de Empresas</a> /
					<a href="{% url 'empresas:detalhe_empresa' object.pk %}">Detalhe da Empresa</a> /
					Editar Empresa
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-12">
                            {% bootstrap_label 'Razão Social<span>*</span>' label_for='id_razao_social' %}
                            {% bootstrap_field form.razao_social size='sm' show_label=false %}
                        </div>
                        <div class="col-md-12">
                            {% bootstrap_label 'Nome Fantasia<span>*</span>' label_for='id_nome_fantasia' %}
                            {% bootstrap_field form.nome_fantasia size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Cnpj<span>*</span>' label_for='id_cnpj' %}
                            {% bootstrap_field form.cnpj size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Endereço<span>*</span>' label_for='id_endereco' %}
                            {% bootstrap_field form.endereco size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'E-mail<span>*</span>' label_for='id_email' %}
                            {% bootstrap_field form.email size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Telefone<span>*</span>' label_for='id_telefone' %}
                            {% bootstrap_field form.telefone size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'empresas:lista_empresas' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/empresas/templates/empresas/lista_empresas.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Empresas</h3>
			<h6>Lista de Empresas</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header'>
				<form action="." method="GET" class="d-flex navbar-form">
					<div class="form-group">
						<input class="form-control me-2" type="search" name="busca" value="" placeholder="Pesquisar" aria-label="Search">
					</div>
					<button class="btn btn-light" type="submit">
						<span class="fa fa-search"></span>
					</button>
				</form>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					Lista de Empresas
				</p>
			</div>
			<div class='card-body'>
				{% if object_list %}
					<div class="table-responsive">
						<table class="table custom-table">
							<thead class="table-dark">
								<tr>
									<th scope="col">Razão Social</th>
									<th scope="col">Nome Fantasia</th>
									<th scope="col">Cnpj</th>
									<th scope="col">E-mail</th>
									<th scope="col">Telefone</th>
								</tr>
							</thead>
							<tbody>
							{% for empresa in object_list %}
								<tr scope="row">
									<td>
										<a href="{% url 'empresas:detalhe_empresa' empresa.pk %}">{{ empresa.razao_social }}</a>
									</td>
									<td>{{ empresa.nome_fantasia }}</td>
									<td>{{ empresa.cnpj }}</td>
									<td>{{ empresa.email }}</td>
									<td>{{ empresa.telefone }}</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<div class="alert alert-danger alert-list" role="alert">
						<div class="alert-title">
							<i class="fas fa-exclamation-circle alert-icon"></i>
						</div>
						<div class="alert-content">
							Empresa não Cadastrada!
						</div>
					</div>
				{% endif %}
				<div class="table-button">
					<a href="{% url 'empresas:nova_empresa' %}" class="btn btn-success" title="Adicionar empresa">
						<i class="fas fa-plus"></i>
						Empresa
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps/empresas/templates/empresas/nova_empresa.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}


{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block title %}{% endblock %}

{% block content %}
<div class="row col-12">
	<div class="content-header">
		<hgroup class="content-header-title">
			<h3>Empresas</h3>
			<h6>Cadastro de Empresa</h6>
		</hgroup>
		<div class="content-header-pages">
		</div>
	</div>
	<div class='container'>
		<div class='card'>
			<div class='card-header header-title'>
				<p>
					<a href="{% url 'core:home' %}">Home</a> /
					<a href="{% url 'empresas:lista_empresas' %}">Lista de Empresas</a> /
					Cadastro de Empresa
				</p>
			</div>
			<div class='card-body'>
				<form action="." method="post" class="form">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-12">
                            {% bootstrap_label 'Razão Social<span>*</span>' label_for='id_razao_social' %}
                            {% bootstrap_field form.razao_social size='sm' show_label=false %}
                        </div>
                        <div class="col-md-12">
                            {% bootstrap_label 'Nome Fantasia<span>*</span>' label_for='id_nome_fantasia' %}
                            {% bootstrap_field form.nome_fantasia size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Cnpj<span>*</span>' label_for='id_cnpj' %}
                            {% bootstrap_field form.cnpj size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Endereço<span>*</span>' label_for='id_endereco' %}
                            {% bootstrap_field form.endereco size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'E-mail<span>*</span>' label_for='id_email' %}
                            {% bootstrap_field form.email size='sm' show_label=false %}
                        </div>
                        <div class="col-md-6">
                            {% bootstrap_label 'Telefone<span>*</span>' label_for='id_telefone' %}
                            {% bootstrap_field form.telefone size='sm' show_label=false %}
                        </div>
                        <div class="button-form col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-save"></i>
                                Salvar
                            </button>
                            <a href="{% url 'empresas:lista_empresas' %}" type="button" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i>
                                Cancelar
                            </a>
                            <div>
                                <small><p>Campos com (<span>*</span>) são Obrigatórios</p></small>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock %}